tic
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Alistair\Documents\MATLAB\test.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/06 15:32:26

%% Initialize variables.
filename = 'pyrometer1\43\0.805.pcd';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%6f%7f%4f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
test = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','VarName2','VarName3','VarName4'});

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;
%test=table2array(table);
X=test(:,1);
X=table2array(X);
XCo=-((X));
Y=test(:,2);
Y=table2array(Y);
YCo=((Y));
Z=test(:,3);
Z=table2array(Z);
 
xmin=min(XCo);
xmax=max(XCo);
ymin=min(YCo);
ymax=max(YCo);
figure('units','normalized','outerposition',[0 0 1 1]);
x=XCo;
y=YCo;
z=Z;
scatter3(x,y,z,[],z,'filled') 
view(0,90);
caxis([800 1760]);
colormap jet;
colorbar;

axis([15500 19000 -22000 -11000]);
toc
tic
saveas(gcf,'test2.tif')
close(gcf)
toc